spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://sweethome.crgu4udnh0nv.ap-northeast-2.rds.amazonaws.com:3306/sweethomeDB
    username: root
    password: vw231429

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type: trace