spring:
  profiles:
    active: local
    include: aws

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true
    defer-datasource-initialization: true

server:
  address: 0.0.0.0
  port: 9000
  servlet:
    session:
      cookie:
        http-only: true
        same-site: none

logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR