spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://perillaleaves.cxvfbpskmkd3.ap-northeast-2.rds.amazonaws.com:3306/project
    username: admin
    password: 12341234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type: trace