spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/sweethome
    username: root
    password: 419914

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

server:
  address: 0.0.0.0
  port: 80
  servlet:
    session:
      timeout: 1800
      cookie:
        http-only: true
        same-site: none