spring:
  profiles:
    active: local
    include: aws

  jpa:
    defer-datasource-initialization: true

server:
  address: 0.0.0.0
  port: 80
  servlet:
    session:
      cookie:
        http-only: true
        same-site: none

logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR